sonar.projectKey=taha-kms_skillsync
sonar.organization=taha-kms
sonar.projectName=SkillSync

sonar.sources=backend/app
sonar.tests=backend/tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.exclusions=docs/**,agent-skills/**,**/node_modules/**,**/.next/**,**/__pycache__/**,**/migrations/**

sonar.python.coverage.reportPaths=backend/coverage.xml
